name: Train Model

on:
  push:
    branches: [ main ]

jobs:
  features:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v4
      with: { python-version: '3.11' }

    - name: Install deps
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Start temp MLflow
      uses: ./.github/actions/start-mlflow

    - name: Run feature pipeline
      run: python3 pipelines/feature.py --environment=pypi run

    - name: Upload pre-processed data
      uses: actions/upload-artifact@v4
      with:
        name: train-data
        path: data/preprocessed/train_data.csv

  training:
    needs: features
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v4
      with: { python-version: '3.11' }

    - name: Install deps
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Download pre-processed data
      uses: actions/download-artifact@v4
      with:
        name: train-data
        path: data/preprocessed

    - name: Start temp MLflow
      uses: ./.github/actions/start-mlflow

    - name: Run training pipeline
      run: python3 pipelines/training.py --environment=pypi run

    - name: Upload trained model
      uses: actions/upload-artifact@v4
      with:
        name: trained-model
        path: mlruns/**/artifacts/model

  inference:
    needs: training
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v4
      with: { python-version: '3.12' }

    - name: Install deps
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Download trained model
      uses: actions/download-artifact@v4
      with:
        name: trained-model
        path: mlruns

    - name: Start temp MLflow
      uses: ./.github/actions/start-mlflow

    - name: Run inference
      run: python3 pipelines/inference.py --environment=pypi run
